# Generated by Django 3.2.5 on 2022-07-24 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('museum_api', '0002_alter_image_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
    ]
